name: STAGING - Build and Deploy

on:
  workflow_dispatch:
    inputs: {}

env:
  GKE_PROJECT: ${{ secrets.GCP_PROJECT_ID_STG }}
  GCR_GKE_PROJECT: kpn-platform-components
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: asia-south1
  IMAGE: core-user-service
  REGISTRY_HOSTNAME: us-docker.pkg.dev
  REPOSITORY: us.gcr.io
  APP_NAME: core-user-service

jobs:
  node-build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_PRIVATE_KEY_STG }}

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_STG }}
          project_id: ${{ secrets.GCP_PROJECT_ID_STG }}
          location: "asia-south1"

      - name: build-login-publish-docker image
        uses: ebomart/build-publish-docker-artifact@main
        with:
          registry_host: $REGISTRY_HOSTNAME
          gke_project: $GCR_GKE_PROJECT
          repository: $REPOSITORY
          image_name: $IMAGE
          google_private_key: ${{ secrets.GOOGLE_PRIVATE_KEY_STG }}
          sha: ${{ github.sha }}
          docker_build_args: "--build-arg NPM_TOKEN=$NPM_TOKEN"
          npm_token: ${{ secrets.NPM_TOKEN }}

      # Install helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        env:
          HELM_OPTS: --set-string environmentVariables.GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID_STG }}
        run: |
          helm upgrade --install --wait core-user-service deployment/charts/$APP_NAME --namespace core-commerce $HELM_OPTS --set image.tag=$GITHUB_SHA  -f deployment/charts/config/values-staging.yaml
